# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: tspg
channels:
  - defaults
dependencies:
  - matplotlib >= 3.5.0
  - numpy
  - pandas == 0.24.0
  - pip
  - pip:
    - tensorflow>=2.5.0
    - tensorflow-probability>=0.8.0
    - --pre umap-learn
    - umap 
  - python=3.7
  - scikit-learn
  - seaborn
